pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        dir('stats-app-main-be-service') {
          git branch: 'master', credentialsId: 'my-cred', url: 'https://github.com/ktadiallo/formsdev-bd.git'
        }
        dir('stats-app-fe') {
          git branch: 'master', credentialsId: 'my-cred', url: 'https://github.com/SultanHedfors/stats-app-fe.git'
        }
        dir('schedule-report-kafka-producer') {
          git branch: 'master', credentialsId: 'my-cred', url: 'https://github.com/SultanHedfors/schedule-report-kafka-producer.git'
        }
        dir('notification-sender') {
          git branch: 'master', credentialsId: 'my-cred', url: 'https://github.com/SultanHedfors/notification-sender.git'
        }
      }
    }

    stage('Build & Test BE') {
      parallel {
        stage('main-be-service') {
          agent { docker { image 'maven:3.6.3-openjdk-11' } }
          steps {
            dir('stats-app-main-be-service') { sh 'mvn clean package' }
          }
        }
        stage('schedule-producer') {
          agent { docker { image 'maven:3.6.3-openjdk-11' } }
          steps {
            dir('schedule-report-kafka-producer') { sh 'mvn clean package' }
          }
        }
        stage('notification-sender') {
          agent { docker { image 'maven:3.6.3-openjdk-11' } }
          steps {
            dir('notification-sender') { sh 'mvn clean package' }
          }
        }
      }
    }

    stage('Build FE') {
      agent { docker { image 'node:22.14-alpine' } }
      steps {
        dir('stats-app-fe') {
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }

    stage('Build Docker Images') {
      agent any
      steps {
        dir('stats-app-main-be-service')           { sh 'docker build -t stats-app-main-be-service:latest .' }
        dir('schedule-report-kafka-producer')     { sh 'docker build -t schedule-report-kafka-producer:latest .' }
        dir('notification-sender')                { sh 'docker build -t notification-sender:latest .' }
        dir('stats-app-fe')                        { sh 'docker build -t stats-app-fe:latest .' }
      }
    }

    stage('Compose Up') {
      agent any
      steps {
        dir('stats-app-main-be-service') {
          sh 'docker-compose up -d'
        }
      }
    }
  }

  post {
    always {
      junit 'stats-app-main-be-service/target/surefire-reports/*.xml'
      archiveArtifacts artifacts: 'stats-app-main-be-service/target/*.jar', fingerprint: true
    }
    success {
      echo 'Build i testy OK!'
    }
    failure {
      echo 'Coś nie działa, sprawdź logi.'
    }
  }
}
