#version: '3.8'
#
#services:
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:firebirdsql://host.docker.internal:3050/C:/databases/example.fdb
#      SPRING_DATASOURCE_USERNAME: sysdba
#      SPRING_DATASOURCE_PASSWORD: masterkey
#
#volumes:
#  firebird-data:
